// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutOrganizer.Api.Data;

#nullable disable

namespace WorkoutOrganizer.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903143154_UpdateWorkoutExercise")]
    partial class UpdateWorkoutExercise
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.Exercise", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Attribution")
                        .HasColumnType("TEXT")
                        .HasColumnName("attribution");

                    b.Property<string>("BodyPart")
                        .HasColumnType("TEXT")
                        .HasColumnName("body_part");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Equipment")
                        .HasColumnType("TEXT")
                        .HasColumnName("equipment");

                    b.Property<string>("GifUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("gif_url");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT")
                        .HasColumnName("image");

                    b.Property<string>("MediaId")
                        .HasColumnType("TEXT")
                        .HasColumnName("media_id");

                    b.Property<string>("MuscleGroup")
                        .HasColumnType("TEXT")
                        .HasColumnName("muscle_group");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Target")
                        .HasColumnType("TEXT")
                        .HasColumnName("target");

                    b.HasKey("Id");

                    b.ToTable("exercises", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("HashPass")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hash_pass");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("refresh_token_expiry");

                    b.HasKey("Id");

                    b.ToTable("user", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.Workout", b =>
                {
                    b.Property<int>("WorkoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("workout_id");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("WorkoutId");

                    b.HasIndex("UserId");

                    b.ToTable("workout", (string)null);
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.WorkoutExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dia");

                    b.Property<string>("ExerciseId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacao");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordem");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("workout_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId", "Dia", "Ordem")
                        .IsUnique();

                    b.ToTable("workout_exercise", null, t =>
                        {
                            t.HasCheckConstraint("CK_workout_exercise_dia", "dia IN ('segunda','terça','quarta','quinta','sexta','sabado','domingo')");
                        });
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.Workout", b =>
                {
                    b.HasOne("WorkoutOrganizer.Api.Entities.User", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.WorkoutExercise", b =>
                {
                    b.HasOne("WorkoutOrganizer.Api.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkoutOrganizer.Api.Entities.Workout", "Workout")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.User", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.Workout", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
