// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutOrganizer.Api.Data;

#nullable disable

namespace WorkoutOrganizer.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.Exercise", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Attribution")
                        .HasColumnType("TEXT")
                        .HasColumnName("attribution");

                    b.Property<string>("BodyPart")
                        .HasColumnType("TEXT")
                        .HasColumnName("body_part");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Equipment")
                        .HasColumnType("TEXT")
                        .HasColumnName("equipment");

                    b.Property<string>("GifUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("gif_url");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT")
                        .HasColumnName("image");

                    b.Property<string>("MediaId")
                        .HasColumnType("TEXT")
                        .HasColumnName("media_id");

                    b.Property<string>("MuscleGroup")
                        .HasColumnType("TEXT")
                        .HasColumnName("muscle_group");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Target")
                        .HasColumnType("TEXT")
                        .HasColumnName("target");

                    b.HasKey("Id");

                    b.ToTable("exercises", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.ExerciseCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("ConcludedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("concluded_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<bool>("Feito")
                        .HasColumnType("INTEGER")
                        .HasColumnName("feito");

                    b.Property<int>("WorkoutExerciseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("workout_exercise_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutExerciseId", "Date")
                        .IsUnique();

                    b.ToTable("workout_exercise_completion", (string)null);
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.ExerciseI18n", b =>
                {
                    b.Property<string>("ExerciseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Lang")
                        .HasColumnType("TEXT")
                        .HasColumnName("lang");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT")
                        .HasColumnName("instructions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NameNorm")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name_norm");

                    b.HasKey("ExerciseId", "Lang");

                    b.ToTable("exercise_i18n", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.ExerciseInstruction", b =>
                {
                    b.Property<string>("ExerciseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Lang")
                        .HasColumnType("TEXT")
                        .HasColumnName("lang");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.HasKey("ExerciseId", "Lang");

                    b.ToTable("exercise_instructions", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.ExerciseInstructionStep", b =>
                {
                    b.Property<string>("ExerciseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Lang")
                        .HasColumnType("TEXT")
                        .HasColumnName("lang");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("step_order");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.HasKey("ExerciseId", "Lang", "StepOrder");

                    b.ToTable("exercise_instruction_steps", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.ExerciseInstructionStepI18n", b =>
                {
                    b.Property<string>("ExerciseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Lang")
                        .HasColumnType("TEXT")
                        .HasColumnName("lang");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("step_order");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.HasKey("ExerciseId", "Lang", "StepOrder");

                    b.ToTable("exercise_instruction_step_i18n", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.ExerciseNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CompletionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completion_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CompletionId")
                        .IsUnique();

                    b.ToTable("exercise_note", (string)null);
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.ExerciseNoteSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("NoteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("note_id");

                    b.Property<int>("SetNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("set_number");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("NoteId", "SetNumber")
                        .IsUnique();

                    b.ToTable("exercise_note_set", null, t =>
                        {
                            t.HasCheckConstraint("CK_exercise_note_set_weight", "weight > 0 AND weight <= 1000");
                        });
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.ExerciseSecondaryMuscle", b =>
                {
                    b.Property<string>("ExerciseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Muscle")
                        .HasColumnType("TEXT")
                        .HasColumnName("muscle");

                    b.HasKey("ExerciseId", "Muscle");

                    b.ToTable("exercise_secondary_muscles", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.MuscleMapping", b =>
                {
                    b.Property<string>("Term")
                        .HasColumnType("TEXT")
                        .HasColumnName("term");

                    b.Property<string>("MuscleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("muscle_id");

                    b.HasKey("Term", "MuscleId");

                    b.ToTable("muscle_mapping", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.MuscleTerm", b =>
                {
                    b.Property<string>("Term")
                        .HasColumnType("TEXT")
                        .HasColumnName("term");

                    b.Property<string>("LabelPt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label_pt");

                    b.HasKey("Term");

                    b.ToTable("muscle_term", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.TermI18n", b =>
                {
                    b.Property<string>("Kind")
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Term")
                        .HasColumnType("TEXT")
                        .HasColumnName("term");

                    b.Property<string>("Lang")
                        .HasColumnType("TEXT")
                        .HasColumnName("lang");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.HasKey("Kind", "Term", "Lang");

                    b.ToTable("term_i18n", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("HashPass")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hash_pass");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("refresh_token_expiry");

                    b.HasKey("Id");

                    b.ToTable("user", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.Workout", b =>
                {
                    b.Property<int>("WorkoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("workout_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("WorkoutId");

                    b.HasIndex("UserId");

                    b.ToTable("workout", (string)null);
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.WorkoutExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CustomName")
                        .HasColumnType("TEXT")
                        .HasColumnName("custom_name");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dia");

                    b.Property<string>("ExerciseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacao");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordem");

                    b.Property<string>("Series")
                        .HasColumnType("TEXT")
                        .HasColumnName("series");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("workout_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId", "Dia", "Ordem")
                        .IsUnique();

                    b.ToTable("workout_exercise", null, t =>
                        {
                            t.HasCheckConstraint("CK_workout_exercise_dia", "dia IN ('segunda','terça','quarta','quinta','sexta','sabado','domingo')");

                            t.HasCheckConstraint("CK_workout_exercise_source", "(exercise_id IS NULL AND custom_name IS NOT NULL) OR (exercise_id IS NOT NULL AND custom_name IS NULL)");
                        });
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.ExerciseCompletion", b =>
                {
                    b.HasOne("WorkoutOrganizer.Api.Entities.WorkoutExercise", "WorkoutExercise")
                        .WithMany()
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutExercise");
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.ExerciseNote", b =>
                {
                    b.HasOne("WorkoutOrganizer.Api.Entities.ExerciseCompletion", "Completion")
                        .WithOne()
                        .HasForeignKey("WorkoutOrganizer.Api.Entities.ExerciseNote", "CompletionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Completion");
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.ExerciseNoteSet", b =>
                {
                    b.HasOne("WorkoutOrganizer.Api.Entities.ExerciseNote", "Note")
                        .WithMany("Sets")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.MuscleMapping", b =>
                {
                    b.HasOne("WorkoutOrganizer.Api.Entities.MuscleTerm", "MuscleTerm")
                        .WithMany("Mappings")
                        .HasForeignKey("Term")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MuscleTerm");
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.Workout", b =>
                {
                    b.HasOne("WorkoutOrganizer.Api.Entities.User", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.WorkoutExercise", b =>
                {
                    b.HasOne("WorkoutOrganizer.Api.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorkoutOrganizer.Api.Entities.Workout", "Workout")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.ExerciseNote", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.MuscleTerm", b =>
                {
                    b.Navigation("Mappings");
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.User", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("WorkoutOrganizer.Api.Entities.Workout", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
